### PR TITLE
Compiles under osx with golang 1.9

### LINKED ISSUE #12: compile fails on darwin go1.9
It looks like this issue is new in go 1.9:

```
$ go version
go version go1.9 darwin/amd64
$ go build .
# github.com/boombuler/hid
./hid_darwin.go:32: constant 18446744073172681404 overflows C.IOReturn
./hid_darwin.go:34: constant 18446744073172681405 overflows C.IOReturn
./hid_darwin.go:36: constant 18446744073172681406 overflows C.IOReturn
./hid_darwin.go:38: constant 18446744073172681407 overflows C.IOReturn
./hid_darwin.go:40: constant 18446744073172681408 overflows C.IOReturn
./hid_darwin.go:42: constant 18446744073172681409 overflows C.IOReturn
./hid_darwin.go:44: constant 18446744073172681410 overflows C.IOReturn
./hid_darwin.go:46: constant 18446744073172681411 overflows C.IOReturn
./hid_darwin.go:48: constant 18446744073172681412 overflows C.IOReturn
./hid_darwin.go:50: constant 18446744073172681413 overflows C.IOReturn
./hid_darwin.go:50: too many errors
```

`kIOReturnError` is:

```
IOKit.framework/Versions/A/Headers/IOReturn.h
85:#define kIOReturnError           iokit_common_err(0x2bc) // general error
```

Which leads into a rathole of #defines which I've not yet investigated. :(

### PR DESCRIPTION
**Pull request by ethanfrey**
This fixes https://github.com/boombuler/hid/issues/12

Getting an int, but constants defined as uint64. Simple type-cast lets it compile, and I get the proper error messages in manual testing on osx.

### CODE REVIEW

File: hid_darwin.go [hunk 1]
```diff
@@ -30,7 +30,8 @@ import (
 	"unsafe"
 )
 
-func ioReturnToErr(ret C.IOReturn) error {
+func ioReturnToErr(ret_ C.IOReturn) error {
+	ret := uint64(ret_)
 	switch ret {
```
Comment (titanous) [inline hid_darwin.go]: I believe this could be simplified to:

```go
switch uint64(ret) {
```

Comment (ethanfrey) [reply hid_darwin.go]: Nice tip. Fixed up code.

**Comment by titanous** [comment]
Thanks!
